### PR TITLE
Feature/bugfix unexpected form data crash

### PR DESCRIPTION
**Pull request by lukevanin**
- Fixes issue #4 : App crash : AttributeError: 'NoneType' object has no attribute 'select'
- Update readme with macOS instructions.

### CODE REVIEW

File: Cr3d0v3r.py [hunk 1]
```diff
@@ -39,19 +39,22 @@ def login( name ,dic ,email ,pwd ):
...
+		browser.submit_selected()
+		#Now let's check if it was success by trying to use the same form again and if I could use it then the login not success
 		browser.select_form(form)
 		browser.close()
 		return "{2} -[{1}{3} {0} {4}{2}] Login unsuccessful!{4}".format(name,R,W,Bold,end)
 	except ms.utils.LinkNotFoundError:
 		browser.close()
 		return "{2} -[{1}{3} {0} {4}{2}] Login successful !{4}".format(name,G,W,Bold,end)
+	except :
+		browser.close
```
Comment (Ne02ptzero) [inline Cr3d0v3r.py]: Didn't you forgot ```()``` at the end of the line?

File: README.md [hunk 2]
```diff
@@ -52,6 +52,17 @@ pip3 install -r requirements.txt
 python Cr3dOv3r.py -h
 ```
 
+**+For macOS :**
+```
+git clone https://github.com/D4Vinci/Cr3dOv3r.git
+chmod -R 777 Cr3dOv3r
+cd Cr3dOv3r
+pip install -r requirements.txt
+python Cr3dOv3r.py -h
```
Comment (Ne02ptzero) [inline README.md]: How does brew / XCode handles concurrent versions of python ? When you call ```python```, are you sure that it is ```python3``` that is launched, and not ```python2``` ?

Comment (lukevanin) [reply README.md]: Running `python` on MacOS uses the system version (2.7 on Sierra). Even though the docs says v3 is required, the script seems to work with v2.7.

Comment (lukevanin) [reply README.md]: Updated docs for using Python 3 on MacOS. 
1. Should I remove the reference to v2.7? 
2. Should I include the steps for installing Homebrew and Python3 (currently external link)?

**Comment by lukevanin** [comment]
Updated from feedback. Please review.

File: README.md (hunk 2 above)
Comment (Ne02ptzero) [reply README.md]: I don't know, it depends on @D4Vinci will's to maintain a script on two different versions of python (There are no differences now, could be in the future). His call.
As for the documentation, I personally thinks that an external links is good enough, since you don't want to make an update every time the python or the homebrew community makes a change on how to install their software.

**Comment by D4Vinci** [comment]
The main file logic is not correct because it should find the form in the first time if not then the data given is wrong not success
And for the README.md the tool is not working with python 2 believe me mechanicalsoup is not Python 2 compatible!

**Comment by lukevanin** [comment]
1. The exception handler in the code catches the runtime exception that occurs when the form has missing fields. This allows the script to fail gracefully and continue running if there is an error with one of the web sites. Without this exception handler, the script terminates if there is a runtime error. See the referenced issue for the runtime error that this addresses (#4).

2. If you check the GitHub repo for [mechanicalsoup](https://github.com/MechanicalSoup/MechanicalSoup), you will see that it is compatible with python 2.7, which is the default python on macOS Sierra.

**Comment by D4Vinci** [comment]
Okay I already updated the tool yesterday thank you
